# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 15:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=6)),
                ('name', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_id', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('birthday', models.DateField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Department')),
            ],
        ),
        migrations.CreateModel(
            name='FulltimeEmployer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_salary', models.DecimalField(decimal_places=1, max_digits=15)),
                ('salary_level', models.FloatField()),
                ('allowance', models.DecimalField(decimal_places=1, max_digits=15)),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Employer', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParttimeEmployer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_salary', models.DecimalField(decimal_places=1, max_digits=15)),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Employer', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParttimeSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_day_number', models.PositiveSmallIntegerField()),
                ('total_salary', models.DecimalField(decimal_places=1, max_digits=15)),
                ('part_time_employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.ParttimeEmployer')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='parttimesalary',
            name='working_month_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.WorkingMonth', unique=True),
        ),
    ]
