# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulltimeemployer',
            name='employer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='src.Employer'),
        ),
        migrations.AlterField(
            model_name='parttimeemployer',
            name='employer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='src.Employer'),
        ),
        migrations.AlterField(
            model_name='parttimesalary',
            name='working_month_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.WorkingMonth'),
        ),
    ]
