# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20171012_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulltimeSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_day_number', models.PositiveSmallIntegerField()),
                ('total_salary', models.DecimalField(decimal_places=1, max_digits=15)),
                ('full_time_employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.FulltimeEmployer')),
                ('working_month_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.WorkingMonth')),
            ],
        ),
    ]
