# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20171013_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulltimesalary',
            name='working_day_number',
        ),
    ]
