# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20171013_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulltimesalary',
            name='total_salary',
            field=models.DecimalField(decimal_places=1, max_digits=20),
        ),
        migrations.AlterField(
            model_name='parttimesalary',
            name='total_salary',
            field=models.DecimalField(decimal_places=1, max_digits=20),
        ),
    ]
